# Site settings
title: Romina Caraba-Thampi
description: Personal Website
baseurl: ""  # Base URL should be empty unless it's a subpath (remove domain)
url: "https://rominacarabathampi.ca"

# User settings
username: "Romina Caraba"
user_description: |
  Hi there! I’m Romina Caraba-Thampi, a Data Scientist with a background in machine learning, backend development, and analytics.

  I currently work at Equitable, where I collaborate closely with underwriting teams to build predictive models and data-driven tools using Python and SQL. My work focuses on enhancing underwriting decision systems through automated daily and monthly reporting pipelines, reducing manual workload and enabling faster, more informed risk assessments.

  Previously, I worked at Metrolinx, where I developed predictive models and analytics solutions to optimize transportation systems and support operational planning.

  With over five years in tech, my experience spans data science, software engineering, and teaching. I’ve worked with Python, SQL, Go, R, and PHP, along with cloud and analytics tools such as AWS, GCP, Power BI, and Docker.

  Whether it’s building scalable data pipelines, designing machine learning models, or creating intuitive dashboards, I specialize in transforming complex data into clear, actionable insights that drive real-world impact.

  Beyond my day-to-day work, I’m passionate about mentoring and supporting others in tech. I offer resume reviews, GitHub portfolio optimization, and mock interviews—helping individuals break into the industry with confidence.
user_title: "Data Scientist"
email: "romina.caraba@gmail.com"
# twitter_username: "codingroses"
github_username: "rominacarabathampi"
instagram_username: "codingroses"
linkedin_username: "rominacarabathampi"

# Google Analytics
google-analytics:
  id: ""

# Excluded files from Jekyll build
exclude:
  - package.json
  - src
  - node_modules
