# Site settings
title: Romina Caraba-Thampi
description: Personal Website
baseurl:  https://rominacarabathampi.ca
url:  https://rominacarabathampi.ca

# User settings
username: Romina Caraba
user_description: I am a developer/analyst currently residing in Waterloo, Canada. My previous work experience includes teaching coding courses at Centennial College, software engineering, backend developer and machine learning engineer positions.
user_title: Developer / Analyst
email: romina.caraba@gmail.com
twitter_username: codingroses
github_username:  rominacarabathampi
instagram_username: codingroses
linkedin_username: rominacarabathampi

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
