# Site settings
title: Romina Caraba-Thampi
description: Personal Website
baseurl:  https://rominacarabathampi.ca
url:  https://rominacarabathampi.ca

# User settings
username: Romina Caraba
user_description: Hi there! 👋 I'm Romina Caraba-Thampi, a Data Scientist with a background in machine learning, backend development, and analytics. I currently work at Metrolinx, where I build predictive models and data-driven solutions to optimize transportation systems.

With over five years in tech, my experience spans data science, software engineering, and teaching. I’ve worked with Python, SQL, Go, R, PHP, and a variety of cloud and analytics tools, including AWS, GCP, Power BI, and Docker. Whether it's building scalable data pipelines, designing ML models, or creating interactive dashboards, I love turning complex data into actionable insights.

I also enjoy mentoring and supporting the tech community—offering resume reviews, GitHub portfolio optimization, and mock interviews to help others break into tech.
user_title: Data Scientist
email: romina.caraba@gmail.com
twitter_username: codingroses
github_username:  rominacarabathampi
instagram_username: codingroses
linkedin_username: rominacarabathampi

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
