# Site settings
title: Romina Caraba-Thampi
description: Personal Website
baseurl:  https://rominacarabathampi.ca
url:  https://rominacarabathampi.ca

# User settings
username: Romina Caraba
user_description: I am a software engineer currently residing in Waterloo, Canada. My previous work experience include backend developer and machine learning engineer positions.
user_title: Software Engineer
email: romina.caraba@gmail.com
twitter_username: codingroses
github_username:  rominacarabathampi
instagram_username: codingroses

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
